// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVFkV-CWFFQ00fWuNS4hYG4s9EX5rira0',
    appId: '1:175359432700:web:7e52dd9b2867e096bcc479',
    messagingSenderId: '175359432700',
    projectId: 'internshipfirstproject',
    authDomain: 'internshipfirstproject.firebaseapp.com',
    storageBucket: 'internshipfirstproject.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-s_8dUf8bP7LuLq1XHVJ3DrgW6dAeAn8',
    appId: '1:175359432700:android:c139fe8c8deae4c0bcc479',
    messagingSenderId: '175359432700',
    projectId: 'internshipfirstproject',
    storageBucket: 'internshipfirstproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPfRf3EOZDr0501rNWEd0WX3jHpdiG0b8',
    appId: '1:175359432700:ios:d9d0051d0d78a43cbcc479',
    messagingSenderId: '175359432700',
    projectId: 'internshipfirstproject',
    storageBucket: 'internshipfirstproject.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPfRf3EOZDr0501rNWEd0WX3jHpdiG0b8',
    appId: '1:175359432700:ios:d9d0051d0d78a43cbcc479',
    messagingSenderId: '175359432700',
    projectId: 'internshipfirstproject',
    storageBucket: 'internshipfirstproject.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVFkV-CWFFQ00fWuNS4hYG4s9EX5rira0',
    appId: '1:175359432700:web:7ecd467d7b1b197cbcc479',
    messagingSenderId: '175359432700',
    projectId: 'internshipfirstproject',
    authDomain: 'internshipfirstproject.firebaseapp.com',
    storageBucket: 'internshipfirstproject.firebasestorage.app',
  );
}
